In [0]:
from google.colab import drive
drive.mount('/content/gdrive')
rootpath = 'gdrive/My Drive/Patches_ROC/'

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [0]:
import matplotlib.pyplot as plt
import cv2
import glob
import numpy as np

In [0]:
#Create numpy array of images
X = []
files = glob.glob (rootpath+"*.jpg")
#print(files)
files.sort()
# files = sorted(files)
for myFile in files:
    #print(myFile)
    image = cv2.imread (myFile,0)
    X.append (image)

X = np.array(X)
print('X_data shape:', X.shape)
print(len(X))

X_data shape: (471, 300, 300)
471


In [0]:
y = ['No','No',
     'No','No',
     'No','No',
     'No','Yes','Yes','Yes','No','No','No','No','No','No','No','Yes','No','No','No','Yes',
     'No','No','No','Yes','No','No','No','No','Yes','No','No','No','No','Yes','No','No',
     'No','No','No','No','No','No','No','No','No','No','Yes','No','No','No','No','No',
     'No','No','No','No','No','No','No','No','No','No','No','No','No','No','No','No', #6
     'No','No', 
     'Yes','No',
     'No','No',
     'No','Yes',
     'Yes','Yes',
     'Yes','No',
     'Yes','No', #13
     'No','No','No','No','No','No','No','No','No','No','No','No','No','Yes','No','No', #14
     'No','No','No','No','No','No','No','No','No','No','No','No','No','No','No','No',
     'No','No','No','No','No','No','No','No','No','No','No','Yes','No','No','No','No',
     'No','No','No','No','No','Yes','No','No','No','No','No','No','No','No','No','No',
     'No','No','Yes','No','No','Yes','Yes','No','No','Yes','Yes','Yes','Yes','No','Yes','Yes',
     'No','No',
     'No','No','No','No','No','No','No','No','No','No','Yes','No','No','No','No','No', #20
     'No','No','No','No','No','No','No','No','No',
     'No','No','No','Yes','No','No','Yes','No','No','Yes','No','No','No','No','No','No',
     'No','No','No','Yes','Yes','Yes','No','Yes','Yes',
     'No','No','No','No','No','Yes','No','Yes','No','No','No','No','No','No','No','No', #24
     'No','No',
     'No','Yes','No','No','Yes','Yes','Yes','Yes','Yes',
     'No','Yes',
     'No','No','No','No','Yes','Yes','No','No','No','No','Yes','No','No','No','No','No',
     'Yes','No',
     'No','No','No','No','No','No','No','No','No','Yes','No','No','No','No','Yes','Yes',
     'No','No',
     'No','No','No','Yes','No','No','Yes','Yes','No','No','No','No','No','No','Yes','Yes',
     'Yes','No',
     'Yes','No',
     'No','No','No','No','No','No','No','No','No','No','No','No','No','No','No','No', #35
     'No','No','No','No','No','No','No','No','No','No','No','No','No','No','No','No',
     'No','No','No','No','No','No','No','No','No','Yes','No','No','No','Yes','No','No',
     'No','Yes',
     'No','No',
     'No','No','No','No','No','No','Yes','No','No','No','No','No','No','No','No','No',
     'No','No',
     'No','No','No','No','No','No','No','No','No','No','No','No','No','No','No','No',
     'No','No','No','No','No','No','No','No','No','No','No','No','No','Yes','No','No',
     'No','No',
     'No','No','No','No','No','No','No','No','No','No','No','No','Yes','No','No','No',
     'No','No','No','No','No','No','No','No','No','No','No','No','No','No','Yes','No',
     'No','No','No','No','No','No','No','No','No','Yes','No','No','No','No','No','No',
     'No','No',
     'No','No','No','Yes','No','No','Yes','No','No','No','No','No','Yes','No','No','No' #49
    ]

In [0]:
y = np.asarray(y) 
print(y.shape)

(471,)


In [0]:
print(len(X))
print(len(y))

471
471


In [0]:
from sklearn.utils import shuffle
# X = X.reshape(X.shape[0],X.shape[1]*X.shape[2]).T
# y = y.reshape(y.shape[0],)
X = np.reshape(X, [X.shape[0], X.shape[1]*X.shape[2]])

X, y = shuffle(X, y, random_state=42)

In [0]:
#############################   Random Forest Algorithm  ##############################

In [0]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
print(clf)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators='warn',
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)


In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)
clf.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [0]:
from sklearn.metrics import accuracy_score

preds = clf.predict(X_test)
print("Accuracy:", accuracy_score(y_test,preds))

Accuracy: 0.9791666666666666


In [0]:
#print(preds)
pred_prob = clf.predict_proba(X_test)
#print(pred_prob)

In [0]:
from sklearn.metrics import precision_recall_fscore_support

In [0]:
precision_recall_fscore_support(y_test, preds, average=None)

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


(array([0.97916667, 0.        ]),
 array([1., 0.]),
 array([0.98947368, 0.        ]),
 array([47,  1]))

In [0]:
from sklearn.metrics import f1_score
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import roc_auc_score
print(f1_score(y_test, preds, average=None))

[0.98947368 0.        ]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [0]:
for i in range(len(y_test)):
    if(y_test[i]=='No'):
        #print(y_test[i])
        num = int(0)
        #print(type(num))
        y_test[i]= int(num)
        #print(type(y_test[i]))
        #print(y_test[i])
    else:
        num = int(1)
        y_test[i]=int(num)
        #print(type(y_test[i]))
        
    if(preds[i]=='No'):
        num = int(0)
        preds[i]=int(num)
    else:
        num = int(1)
        preds[i]=int(num)

#print(y_test)
#print(preds)

In [0]:
y_test = list(map(int, y_test)) 
preds = list(map(int, preds)) 

In [0]:
print(roc_auc_score(y_test, preds))

0.5


In [0]:
###############################  Neural Network Algorithm ##############################

In [0]:
from sklearn.model_selection import train_test_split
X_train1, X_test1, y_train1, y_test1 = train_test_split(X, y, test_size = 0.1)

In [0]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(10,10,10))
mlp.fit(X_train1, y_train1)

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(10, 10, 10), learning_rate='constant',
              learning_rate_init=0.001, max_iter=200, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

In [0]:
preds1 = mlp.predict(X_test1)
#print(preds1)

#preds = clf.predict(X_test)
print("Accuracy:", accuracy_score(y_test1,preds1))

Accuracy: 0.9166666666666666


In [0]:
#print(preds)
pred_prob = mlp.predict_proba(X_test1)
#print(pred_prob)

In [0]:
precision_recall_fscore_support(y_test1, preds1, average=None)

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


(array([0.91666667, 0.        ]),
 array([1., 0.]),
 array([0.95652174, 0.        ]),
 array([44,  4]))

In [0]:
from sklearn.metrics import f1_score
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import roc_auc_score
print(f1_score(y_test1, preds1, average=None))

[0.95652174 0.        ]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [0]:
for i in range(len(y_test1)):
    if(y_test1[i]=='No'):
        #print(y_test[i])
        num = int(0)
        #print(type(num))
        y_test1[i]= int(num)
        #print(type(y_test[i]))
        #print(y_test[i])
    else:
        num = int(1)
        y_test1[i]=int(num)
        #print(type(y_test[i]))
        
    if(preds1[i]=='No'):
        num = int(0)
        preds1[i]=int(num)
    else:
        num = int(1)
        preds1[i]=int(num)

#print(y_test)
#print(preds)

In [0]:
y_test1 = list(map(int, y_test1)) 
preds1 = list(map(int, preds1)) 

In [0]:
print(roc_auc_score(y_test1, preds1))

0.5


In [0]:
################################## Support Vector Machine Algorithm ####################################

In [0]:
X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y, test_size = 0.1)

In [0]:
from sklearn import svm
svl = svm.SVC()

In [0]:
svl.fit(X_train2,y_train2)

/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [0]:
preds2 = svl.predict(X_test2)
#print(preds2)

print("Accuracy:", accuracy_score(y_test2,preds2))

Accuracy: 0.75


In [0]:
precision_recall_fscore_support(y_test2, preds2, average=None)

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


(array([0.75, 0.  ]),
 array([1., 0.]),
 array([0.85714286, 0.        ]),
 array([36, 12]))

In [0]:
from sklearn.metrics import f1_score
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import roc_auc_score
print(f1_score(y_test2, preds2, average=None))

[0.85714286 0.        ]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [0]:
for i in range(len(y_test2)):
    if(y_test2[i]=='No'):
        #print(y_test[i])
        num = int(0)
        #print(type(num))
        y_test2[i]= int(num)
        #print(type(y_test[i]))
        #print(y_test[i])
    else:
        num = int(1)
        y_test2[i]=int(num)
        #print(type(y_test[i]))
        
    if(preds2[i]=='No'):
        num = int(0)
        preds2[i]=int(num)
    else:
        num = int(1)
        preds2[i]=int(num)

#print(y_test)
#print(preds)

In [0]:
y_test2 = list(map(int, y_test2)) 
preds2 = list(map(int, preds2)) 

In [0]:
print(roc_auc_score(y_test2, preds2))

0.5
