In [28]:
import glob
import numpy as np
import matplotlib.pyplot as plt
import cv2

In [29]:
#Create numpy array of images
X = []
files = glob.glob ("./Patches_ROC/*.jpg")
# print(type(files))
files.sort()
# files = sorted(files)
for myFile in files:
    #print(myFile)
    image = cv2.imread (myFile,0)
    X.append (image)

X = np.array(X)
print('X_data shape:', X.shape)
print(len(X))

X_data shape: (471, 300, 300)
471


In [30]:
y = ['No','No',
     'No','No',
     'No','No',
     'No','Yes','Yes','Yes','No','No','No','No','No','No','No','Yes','No','No','No','Yes',
     'No','No','No','Yes','No','No','No','No','Yes','No','No','No','No','Yes','No','No',
     'No','No','No','No','No','No','No','No','No','No','Yes','No','No','No','No','No',
     'No','No','No','No','No','No','No','No','No','No','No','No','No','No','No','No', #6
     'No','No', 
     'Yes','No',
     'No','No',
     'No','Yes',
     'Yes','Yes',
     'Yes','No',
     'Yes','No', #13
     'No','No','No','No','No','No','No','No','No','No','No','No','No','Yes','No','No', #14
     'No','No','No','No','No','No','No','No','No','No','No','No','No','No','No','No',
     'No','No','No','No','No','No','No','No','No','No','No','Yes','No','No','No','No',
     'No','No','No','No','No','Yes','No','No','No','No','No','No','No','No','No','No',
     'No','No','Yes','No','No','Yes','Yes','No','No','Yes','Yes','Yes','Yes','No','Yes','Yes',
     'No','No',
     'No','No','No','No','No','No','No','No','No','No','Yes','No','No','No','No','No', #20
     'No','No','No','No','No','No','No','No','No',
     'No','No','No','Yes','No','No','Yes','No','No','Yes','No','No','No','No','No','No',
     'No','No','No','Yes','Yes','Yes','No','Yes','Yes',
     'No','No','No','No','No','Yes','No','Yes','No','No','No','No','No','No','No','No', #24
     'No','No',
     'No','Yes','No','No','Yes','Yes','Yes','Yes','Yes',
     'No','Yes',
     'No','No','No','No','Yes','Yes','No','No','No','No','Yes','No','No','No','No','No',
     'Yes','No',
     'No','No','No','No','No','No','No','No','No','Yes','No','No','No','No','Yes','Yes',
     'No','No',
     'No','No','No','Yes','No','No','Yes','Yes','No','No','No','No','No','No','Yes','Yes',
     'Yes','No',
     'Yes','No',
     'No','No','No','No','No','No','No','No','No','No','No','No','No','No','No','No', #35
     'No','No','No','No','No','No','No','No','No','No','No','No','No','No','No','No',
     'No','No','No','No','No','No','No','No','No','Yes','No','No','No','Yes','No','No',
     'No','Yes',
     'No','No',
     'No','No','No','No','No','No','Yes','No','No','No','No','No','No','No','No','No',
     'No','No',
     'No','No','No','No','No','No','No','No','No','No','No','No','No','No','No','No',
     'No','No','No','No','No','No','No','No','No','No','No','No','No','Yes','No','No',
     'No','No',
     'No','No','No','No','No','No','No','No','No','No','No','No','Yes','No','No','No',
     'No','No','No','No','No','No','No','No','No','No','No','No','No','No','Yes','No',
     'No','No','No','No','No','No','No','No','No','Yes','No','No','No','No','No','No',
     'No','No',
     'No','No','No','Yes','No','No','Yes','No','No','No','No','No','Yes','No','No','No' #29
    ]

In [31]:
y = np.asarray(y) 
print(y.shape)

(471,)


In [32]:
img_index = 25
#plt.imshow(X_data1[:,:,:,img_index])
#plt.show()
print(y[img_index])

Yes


In [33]:
print(len(X))
print(len(y))

471
471


In [34]:
from sklearn.utils import shuffle
# X = X.reshape(X.shape[0],X.shape[1]*X.shape[2]).T
# y = y.reshape(y.shape[0],)
X = np.reshape(X, [X.shape[0], X.shape[1]*X.shape[2]])

X, y = shuffle(X, y, random_state=42)

In [35]:
#############################   Random Forest Algorithm  ##############################

In [36]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
print(clf)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)


In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [38]:
from sklearn.metrics import accuracy_score

preds = clf.predict(X_test)
print("Accuracy:", accuracy_score(y_test,preds))

Accuracy: 0.9583333333333334


In [39]:
#print(preds)
pred_prob = clf.predict_proba(X_test)
#print(pred_prob)

In [40]:
from sklearn.metrics import precision_recall_fscore_support

In [41]:
precision_recall_fscore_support(y_test, preds, average=None)

(array([0.9787234, 0.       ]),
 array([0.9787234, 0.       ]),
 array([0.9787234, 0.       ]),
 array([47,  1], dtype=int32))

In [42]:
from sklearn.metrics import f1_score
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import roc_auc_score
print(f1_score(y_test, preds, average=None))

[0.9787234 0.       ]


In [43]:
for i in range(len(y_test)):
    if(y_test[i]=='No'):
        #print(y_test[i])
        num = int(0)
        #print(type(num))
        y_test[i]= int(num)
        #print(type(y_test[i]))
        #print(y_test[i])
    else:
        num = int(1)
        y_test[i]=int(num)
        #print(type(y_test[i]))
        
    if(preds[i]=='No'):
        num = int(0)
        preds[i]=int(num)
    else:
        num = int(1)
        preds[i]=int(num)

#print(y_test)
#print(preds)

In [44]:
y_test = list(map(int, y_test)) 
preds = list(map(int, preds)) 

In [45]:
print(roc_auc_score(y_test, preds))

0.48936170212765956


In [46]:
###############################  Neural Network Algorithm ##############################

In [47]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1)

In [48]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(10,10,10))
mlp.fit(X_train, y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(10, 10, 10), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [49]:
preds1 = mlp.predict(X_test)
#print(preds1)

#preds = clf.predict(X_test)
print("Accuracy:", accuracy_score(y_test,preds1))

Accuracy: 0.9166666666666666


In [50]:
################################## Support Vector Machine Algorithm ####################################

In [51]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1)

In [52]:
from sklearn import svm
svl = svm.SVC()

In [53]:
svl.fit(X_train,y_train)

MemoryError: 

In [ ]:
preds2 = svl.predict(X_test)
#print(preds2)

print("Accuracy:", accuracy_score(y_test,preds2))